# Simple workflow for deploying static content to GitHub Pages
name: Check Adobe Air Cache

on:
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  check-cache:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Adobe AIR SDK
        uses: joshtynjala/setup-adobe-air-action@v2.2.0
